---
repositories:
  - name: "chainlink-ocr-client"
    url: "https://telekom-mms.github.io/web3-helm-charts"

releases:
  - name: "chainlink-ocr-client"
    chart: "chainlink-ocr-client/chainlink-ocr-client"
    version: "1.0.0"
    namespace: "chainlink"
    values:
      - "./values.yaml"
      - postgres.password: {{ requiredEnv "PG_PASSWORD" }}
      - ocr.credentials.api.password: {{ requiredEnv "API_PASSWORD" }}
      - keystorePassword: {{ requiredEnv "KEYSTORE_PASSWORD" }}
...
